"""short_url_index and is_expired added

Revision ID: 452876c3194f
Revises: 75bb7963ccfe
Create Date: 2020-12-15 17:42:13.640100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452876c3194f'
down_revision = '75bb7963ccfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('is_expired', sa.Boolean(), nullable=False))
    op.create_index('links_short_url_not_expired_index', 'links', ['short_url'], postgresql_where=sa.text('NOT is_expired'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('links_short_url_not_expired_index', table_name='links')
    op.drop_column('links', 'is_expired')
    # ### end Alembic commands ###
